server:
  port: 8771
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8765/eureka/
spring:
  application:
    name: service-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: service-hi
          uri: lb://SERVICE-HI
          predicates:
            - Path=/demo/**
          filters:
            - StripPrefix=1
#      routes:
#        - id: after_route
#          uri: http://httpbin.org:80/get
#          filters:
#            - AddRequestHeader=X-Request-Foo, Bar
#            - AddResponseHeader=Set-Cookie,name=kobe
#            - RequestTime=false
#          predicates:
#            - After=2019-05-22T17:42:47.789-07:00[America/Denver]
#        - id: rewritepath_route
#          uri: https://blog.csdn.net
#          predicates:
#            - Path=/foo/**
#          filters:
#            - RewritePath=/foo/(?<segment>.*), /$\{segment}
#        - id: header_route
#          uri: http://httpbin.org:80/get
#          predicates:
#            - Header=X-Request-Id, \d+
#        - id: cookie_route
#          uri: http://httpbin.org:80/get
#          predicates:
#            - Cookie=name, kobe
#        - id: host_route
#          uri: http://httpbin.org:80/get
#          predicates:
#            - Host=**.gaipianer.com
#        - id: method_route
#          uri: http://httpbin.org:80/get
#          predicates:
#            - Method=POST
#        - id: path_route
#          uri: http://httpbin.org:80/get
#          predicates:
#            - Path=/foo/**
#        - id: query_route
#          uri: http://httpbin.org:80/get
#          predicates:
#            - Query=foo
